### PR TITLE
RE #46 - split out related tasks into separate files under the `tasks` dir

### PR DESCRIPTION
**Pull request by u01jmg3**
- Add new lib `gulp-require-tasks` to dynamically create tasks from the `tasks` dir
- Add new `phpcbf` task to use in conjunction with the `phpcs` task
- Update `pagespeed`, `screenshots` and `csslint` tasks to use new syntax
- Update `bower:install` task to use local `bower.json` config file
- Replace `gulp-css-url-adjuster` dependency with `gulp-rework` / `rework-plugin-url` combination
- Wrap `this.emit('end')` in `try`/`catch` for times when the call is not necessary
- Add trailing commas

### CODE REVIEW

**Comment by u01jmg3** [comment]
Ignore circleci - was never setup

**Comment by robertmain** [comment]
> I can't see how it can be called on it's own, without adding it to one of the "main" tasks in gulpfile.js

You should be able to just pass it as an argument to the `gulp` command, like so `gulp generate:screenshots:dist`. Unless I've misunderstood your question?

**Comment by u01jmg3** [comment]
@321zeno: can you approve and merge?

**Comment by 321zeno** [comment]
👍

**Pull request merged**
