### PR TITLE
Addition of `gulp-filelog` for primary tasks

### PR DESCRIPTION
**Pull request by robertmain**
- Use of `gulp-filelog` to print out the files in the pipe if the `--verbose` flag is used

### CODE REVIEW

**Comment by u01jmg3** [comment]
Good addition - will test when I'm back :)

**Comment by u01jmg3** [comment]
As discussed I think this flag could be included in more of the major tasks

**Comment by u01jmg3** [comment]
Will test as soon as I can

**Comment by robertmain** [comment]
:+1:

**Comment by u01jmg3** [comment]
Can you update `package.json` with `gulp-filelog` dependency?

**Pull request merged**
