### PR TITLE
Moves dependencies from batch file to package.json

### PR DESCRIPTION
**Pull request by robertmain**
Also adds in extra meta-data fields and **(deliberately) has a local and a global copy of gulp**.

Failure to have a local gulp results in:
```
$ gulp
[14:19:17] Local gulp not found in ~\Desktop\gulp-starter
[14:19:17] Try running: npm install gulp
```

### CODE REVIEW

**Comment by robertmain** [comment]
I put it in as a local dependency because that then means that we can use the programmatic API instead of just using gulp-shell to run "bower install"

**Comment by u01jmg3** [comment]
Will need to test before I can merge

**Comment by u01jmg3** [comment]
> I put it in as a local dependency because that then means that we can use [the programmatic API](http://bower.io/docs/api/#programmatic-api) instead of just using gulp-shell to run `bower install`

Nice :+1:

**Comment by u01jmg3** [comment]
Closing PR as performed the changes myself in order to make sure nothing was missed - all works well so thanks for suggesting.

Currently seeing an issue with browser-sync (browser-sync-ui 0.5.8) and npm claiming a shasum check failure but have opened up an issue with the author to rectify.

**Pull request closed without merging**
